Create script to assign osg GIDs to OSPool projects (SOFTWARE-5619)
opensciencegrid/osg-comanage-project-usermap pull request #18
Opened 2023-11-16 19:31 UTC by williamnswanson

Initial Commit for project osggid assignment script

2023-11-21 23:02 UTC, jasoncpatton requested changes
See comments, main concern is that there is a possibility for OSG GID collision.

2023-11-21 23:02 UTC, jasoncpatton commented on group_identifier_assigner.py
> +    return -1
This works, but I think you can use a list comprehension directly for `found_list` (`[id["Type"] == id_type for id in id_list]`) rather than creating and consuming a generator, but even better, don't bother with any comparisons except for the `index` lookup using a `try`/`except` to retain the same return value behavior.
```suggestion
def identifier_index(id_list, id_type):
    id_type_list = [id["Type"] for id in id_list]
    try:
        return id_type_list.index(id_type)
    except ValueError:
        return -1
```

2023-11-21 23:02 UTC, jasoncpatton commented on group_identifier_assigner.py
> +OSPOOL_PATTERN_STR = "Yes-"
Nitpick: this is not so much a "pattern" but a "prefix".

2023-11-21 23:02 UTC, jasoncpatton commented on group_identifier_assigner.py
> +                add_identifier_to_group(gid, type="osggid", identifier_name=osggid_to_assign)
I see the logic here in that `highest_osggid` is never able to decrement, but I think there is still a possibility for collision unless `co_groups.json` is already somehow sorted by `osggid` (but happy to be proven wrong!). For instance, suppose we already have assignments (or missing assignments):
```
ProjectA -> 200000
ProjectB -> 200001
ProjectC -> (undefined)
ProjectD -> 200002
```
and `co_groups` happens to go in order of `ProjectA, ProjectB, ProjectC, ProjectD`, I believe that this script will try to assign ProjectC a `osggid` of `200002`.

I think to be certain, the script should go through all the project groups once to fetch the highest existing `osggid` (if any) and only then start assigning new GIDs.

2023-11-22 16:06 UTC, williamnswanson commented on group_identifier_assigner.py
> +OSPOOL_PATTERN_STR = "Yes-"
Gotcha', changed in commit [5dd0437](https://github.com/opensciencegrid/osg-comanage-project-usermap/pull/18/commits/5dd04376a4721ad1a9b7ff0511f4ed9f75284124)

2023-11-22 16:07 UTC, williamnswanson commented on group_identifier_assigner.py
> +    return -1
I've incorporated this into [5dd0437](https://github.com/opensciencegrid/osg-comanage-project-usermap/pull/18/commits/5dd04376a4721ad1a9b7ff0511f4ed9f75284124)

2023-11-22 16:17 UTC, williamnswanson commented on group_identifier_assigner.py
> +                add_identifier_to_group(gid, type="osggid", identifier_name=osggid_to_assign)
Ok, I've moved the assigning out to a separate loop at the end in [575a016](https://github.com/opensciencegrid/osg-comanage-project-usermap/pull/18/commits/575a016d902393d252c002fd71958ebaa3be4cdc)

2023-11-22 19:18 UTC, jasoncpatton requested changes
One small change, otherwise LGTM!

2023-11-22 19:18 UTC, jasoncpatton commented on group_identifier_assigner.py
> +                projects_to_assign_identifiers.append(tuple([gid, project_name]))
You can tack on an extra comma to let Python know you want a 2-tuple using parentheses (i.e. without converting a list):
```suggestion
                projects_to_assign_identifiers.append((gid, project_name,))
```

2023-11-22 19:20 UTC, jasoncpatton approved these changes

2023-11-22 19:54 UTC, merged