Update project_usermap creation script (INF-1060)
opensciencegrid/osg-comanage-project-usermap pull request #19
Opened 2023-11-27 22:17 UTC by williamnswanson

Uses LDAP for determining group membership.

Uses LDAP to determine active users, and only adds a user to the map if they are active (from SOFTWARE-5413)

Still uses the COmanage API to find out which CO groups are projects, but now caches them so if the map needs to be recreated in a short amount of time, it doesn't need to make so many API calls (cache currently stales after 0.5 hours, but changing it should only take changing a global)

2023-11-28 22:00 UTC, williamnswanson commented
From talking with Brian L, projects don't need to be provisioned in LDAP, so assuming that LDAP has all the groups that are projects is an error. The project-usermap script should instead use the COmanage API to find the members of project groups (based on the group member entry's Member field being true)

2023-12-01 22:44 UTC, brianhlin requested changes
@williamnswanson this is a solid first attempt but I'm really interested in having you going back to the drawing board using the `ldap3` library because I think it will simplify a lot. You've got a lot of pounds of code here to parse the shell output and I think as a result, it looks like you've got more data structures than you actually need. With the `ldap3` library, I think you can have two data sources:

1. LDAP: All active users that are part of the relevant AP login group. I'd expect the data struct that you get back to include every group that the user is a member of
2. COManage API: All project groups. It looks like you already have this, more or less, but I reserve the right to pick nits in the future :) 

Then project map construction should just be as simple as iterating through the users and taking the intersection of their groups + (2) above

2023-12-01 22:44 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +import subprocess
I don't think `subprocess` is necessary here as you can use existing `ldap` libraries (see https://github.com/opensciencegrid/topology/blob/master/src/webapp/ldap_data.py#L145-L179).

I'd say generally, you want to use first class libraries instead of `subprocess` callouts as the latter are often pretty brittle. Part of that is that first class libraries will give you Python-native data structures so that you don't have to write hard-to-debug, easy-to-break regular expressions for parsing output.

2023-12-01 22:44 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +]
This assumes a few things that I don't think are necessarily safe to assume:

1. The user running this script can read this file
2. That this file exists

Instead, you should have an option that allows the caller to reference a file containing the password. I prefer that over options specifying the password directly since you don't want the password showing up in plain text in the process tree.

2023-12-01 22:44 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +    "|", "sort",
If you do need to call out to `subprocess`, you certainly don't need pipes. You'll have better output processing tools for you in native Python!

2025-12-02 16:57 UTC, merged