Add local mapfile merging to osg-comanage-project-usermap (INF-2273)
opensciencegrid/osg-comanage-project-usermap pull request #24
Opened 2024-09-05 21:29 UTC by williamnswanson

Initial pass at adding merging of local mapfiles into the mapfile generated by osg-comanage-project-usermap. Use option -i when calling the script and provide a comma-separated list of paths/filenames for the local mapfiles you want merged in.

For Jira issue [INF-2273](https://opensciencegrid.atlassian.net/browse/INF-2273)

2024-09-05 23:25 UTC, brianhlin requested changes
This looks like it'll probably work but I've left a few comments to tighten things up a bit

2024-09-05 23:25 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +                user_groupmap[split_line[1]] = split_line[2].split(",")
```suggestion
            # Split up 3 semantic columns
            split_line = line.split(maxsplit=2)
            if split_line[0] == "*" and len(split_line) == 3:
                user_groupmap[split_line[1]] = set(re.split(r'[ ,]+', split_line[2]))
```

I suspect that valid mapping lines allow for combinations of `,` and ` `. For example:

```
* user project1,project2
```

As well as 

```
* user project1, project2
```

We also should use sets so that we don't end up with any dupes in the project list

2024-09-05 23:25 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +        if op == '-i': options.inputfiles = arg.split(",")
Bah, I forgot that this used `getopt`. This format for the input list stinks (as opposed to specifying `-i` multiple times but I think changing it is out of scope of this PR

2024-09-05 23:25 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +    with open(inputfile) as file:
```suggestion
    with open(inputfile, 'r', encoding='utf-8') as file:
```

Pylint always yells at me about encoding

2024-09-05 23:25 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +            split_line = line.split()
```suggestion
            split_line = line.strip().split(maxsplit=2)
```

I think that you're mainly looking to get rid of the trailing newline here?

2024-09-05 23:25 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +    for inputfile in options.inputfiles:
```suggestion
    for inputfile in options.inputfiles:
```

Let's avoid implicitly required inputs. I'd make the list of input files an explicitly required function arg.

That being said, why create a function specific to merging input files? To me, the following flow makes sense:

1. Create mapping dict for COmanage groups
2. Create mapping dicts for input files
3. Merge all mapping groups

Which looks like 2 new functions to me for 2 and 3

2024-09-05 23:25 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +        for key in merge_material.keys():
How about a for loop + new function-level variable to store the merged dict? That way you're not doing destructive ops on the input arg

2024-09-05 23:25 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +                merge_target[key] = list(set(merge_target[key]))
I think the appropriate data structure is just a dict with users as the keys and projects stored as a `set`. You get the deduplication for free and I can't think of anything list-specific that you need.

2024-09-05 23:25 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +  -i inputfiles       specify a comma-delineated list of local mapfiles to merge into outfile
```suggestion
  -i inputfiles       specify a comma-delimited list of local HTCondor mapfiles to merge into outfile
```

2024-09-06 15:01 UTC, williamnswanson commented on osg-comanage-project-usermap.py
> +                user_groupmap[split_line[1]] = split_line[2].split(",")
Is there intended behavior for specifying the same user multiple times in the *same* mapfile? Are we alright to overwrite the value in the dict for that user with the last set of projects, or should we also be taking the union of all the projects a user is listed with?

2024-09-06 16:39 UTC, williamnswanson commented on osg-comanage-project-usermap.py
> +                user_groupmap[split_line[1]] = split_line[2].split(",")
I've changed the local inputfile parsing method (now called parse_localmap) to use sets of groups/projects, along with merging all groups for a user if the user is listed multiple times in a projectmap.

2024-09-06 18:47 UTC, brianhlin commented on osg-comanage-project-usermap.py
> +                user_groupmap[split_line[1]] = split_line[2].split(",")
> Is there intended behavior for specifying the same user multiple times in the same mapfile?

Not sure what HTCondor's behavior would be here but I would expect it to only honor the first line for the user

>  or should we also be taking the union of all the projects a user is listed with?

I would do a union for all sets of projects

2024-09-06 23:42 UTC, brianhlin approved these changes
LGTM!

2024-09-09 14:25 UTC, merged